### ISSUE TITLE
Unable to get past the grant permissions screen 

### ISSUE THREAD

**Issue by btehan** [dsvi/Pulsar#2]
Hey there.

I installed this via f-droid on my pixel 7 pro and I granted the permission for nearby devices but it stays on the grant permissions screen.  I manually allowed the other permission for notifications, force quit, and reinstalled the app and I still can't get past that.  Any suggestions on what I could try?

Thanks.

**Comment by dsvi** [comment]
My bet is the problem is in Android 13. I don't have such device and never tested for it. But Androids above 12 work differently with Bluetooth permissions. 
[Try this build](https://send.ephemeral.land/download/12b2bed5bde17ea2/#ipmenv4KQmkuoqMPXqG-zg), and tell me how it works.

**Comment by btehan** [comment]
Hey dsvi

Unfortunately the APK won't install:

"Pulsar
App not installed as package appears to be invalid."

**Comment by dsvi** [comment]
Did you uninstal the previous one before instaling this?

**Comment by btehan** [comment]
Yes.

**Comment by dsvi** [comment]
Sry for that. I have signed it now. Should work
[app-release.zip](https://github.com/dsvi/Pulsar/files/11968609/app-release.zip)

**Comment by btehan** [comment]
No worries.

App now installs and works.  I can see the heart rate and battery reading from my device.  Thanks!

**Comment by dsvi** [comment]
Thanks for reporting the issue
